name: Build

on: [push, pull_request]


jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfltk1.3-dev fluid gettext appstream
          sudo apt-get install -y libpixman-1-dev libjpeg-turbo8-dev
          sudo apt-get install -y libgnutls28-dev nettle-dev libgmp-dev
          sudo apt-get install -y libxtst-dev libxdamage-dev libxfixes-dev libxrandr-dev libpam-dev
          sudo apt-get install -y libavcodec-dev libavutil-dev libswscale-dev
          sudo apt-get install -y libgtest-dev
          sudo apt-get install -y libpulse-dev
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: make tarball
      - uses: actions/upload-artifact@v4
        with:
          name: Linux (Ubuntu)
          path: build/tigervnc-*.tar.gz
      - name: Test
        working-directory: build
        run: ctest --test-dir tests/unit/ --output-junit test-results.xml
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-linux
          path: build/tests/unit/test-results.xml

