name: Build

on: [push, pull_request]


jobs:
  build-linux:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfltk1.3-dev fluid gettext appstream
          sudo apt-get install -y libpixman-1-dev libjpeg-turbo8-dev
          sudo apt-get install -y libgnutls28-dev nettle-dev libgmp-dev
          sudo apt-get install -y libxtst-dev libxdamage-dev libxfixes-dev libxrandr-dev libpam-dev
          sudo apt-get install -y libavcodec-dev libavutil-dev libswscale-dev
          sudo apt-get install -y libgtest-dev
          sudo apt-get install -y libpulse-dev
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: make tarball
      - uses: actions/upload-artifact@v4
        with:
          name: Linux (Ubuntu)
          path: build/tigervnc-*.tar.gz
      - name: Test
        working-directory: build
        run: ctest --test-dir tests/unit/ --output-junit test-results.xml
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-linux
          path: build/tests/unit/test-results.xml
          
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
      - name: Install dependencies
        run: |
          pacman --sync --noconfirm --needed \
            make mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
          pacman --sync --noconfirm --needed \
            mingw-w64-x86_64-libjpeg-turbo \
            mingw-w64-x86_64-gnutls mingw-w64-x86_64-pixman \
            mingw-w64-x86_64-nettle mingw-w64-x86_64-gmp \
            mingw-w64-x86_64-gtest
          # MSYS2 only packages FLTK 1.4 now:
          # https://github.com/msys2/MINGW-packages/issues/22769
          pacman --upgrade --noconfirm --needed \
            https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-fltk-1.3.9-2-any.pkg.tar.zst
      - name: Configure
        run: cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Debug -S . -B build
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        env:
          MSYS2_PATH_TYPE: inherit
        run: make installer winvnc_installer
      - uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: build/release/tigervnc*.exe
      - name: Test
        working-directory: build
        run: ctest --test-dir tests/unit/ --output-junit test-results.xml
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-windows
          path: build/tests/unit/test-results.xml
          
  build-packages:
    timeout-minutes: 20
    strategy:
      matrix:
        target:
          - rocky9
          - focal
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      DOCKER: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t tigervnc/$DOCKER .github/containers/$DOCKER
      - name: Build packages
        run: .github/containers/$DOCKER/build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: Packages (${{ matrix.target }})
          path: .github/containers/${{ matrix.target }}/result
